version: '3.8'

services:
  nodejs:
    build: .
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules